package cz.cvut.fel.restauracefel.pokladna.pokladna_gui;

import java.awt.Insets;
import java.awt.Point;
import java.io.FileNotFoundException;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.util.HashSet;
import java.util.Iterator;
import javax.swing.JOptionPane;
import cz.cvut.fel.restauracefel.library.service.ConfigParser;
import cz.cvut.fel.restauracefel.library.service.EmptyListException;
import cz.cvut.fel.restauracefel.pokladna_service.ServiceFacade;
import cz.cvut.fel.restauracefel.library.service.Validator;

/**
 * Trida reprezentujici GUI formular pro vytvareni nove slevy.
 *
 * @author Tomas Hnizdil
 */
public class AssignDiscountForm extends AbstractForm {

    private ChooseDiscountTypeDialog chooseDiscountTypeDialog = null;
    private ChooseMenuItemsDialog chooseMenuItemsDialog = null;
    private CreateDiscountTypeForm createDiscountTypeForm = null;
    private StatusBar statusBar = null;
    private MainFrame parent = null;
    private ConfigParser config = null;
    private HashSet<String> hs = null;
    private Point point = new Point(550, 210);
    enum ValidEnum{Spravne, Sleva, NezaporneCislo, KoeficientNezaporny, JednaPolozka;};

    /**
     * Konstruktor tridy AssignDiscountForm.
     *
     * @param parent
     * @param bar
     * @throws java.rmi.RemoteException
     * @throws java.rmi.NotBoundException
     * @throws java.io.FileNotFoundException
     */
    public AssignDiscountForm(MainFrame parent, StatusBar bar) throws FileNotFoundException, NotBoundException, RemoteException {
        this.parent = parent;
        this.statusBar = bar;
        config = new ConfigParser();
        initComponents();
        refresh();
        clearFields();
    }

    /**
     * Metoda nastavuje popisek s pouzivanou menou a prenastavuje statusBar.
     *
     * @throws java.rmi.RemoteException
     * @throws java.rmi.NotBoundException
     * @throws java.io.FileNotFoundException
     */
    @Override
    protected void refresh() throws FileNotFoundException, NotBoundException, RemoteException {
        jLabelCurrency.setText(",- " + config.getMoney());
        statusBar.setMessage("Tento formulář slouží k vytváření nové slevy.");
    }

    /**
     * Metoda kontrolujici spravnost vyplnenych udaju.
     *
     * @return Vraci index urcujici vstupni komponentu, ktera obsahuje
     * neplatny vstup. Pokud je vse vporadku tak navraci 0.
     */
    private ValidEnum isValidInputComplex() {
        if (!Validator.isText(jTextFieldMenuItems)) return ValidEnum.Sleva;
        if (!Validator.isDouble(jTextFieldSum)) return ValidEnum.NezaporneCislo;
        if (!Validator.isInt(jTextFieldCoefficient)) return ValidEnum.KoeficientNezaporny;
        if (!Validator.isPositiveInt(jTextFieldMenuItems)) return ValidEnum.JednaPolozka;
        return ValidEnum.Spravne;
    }

    /**
     * Metoda ulozi seznam vybranych polozek menu predavany z dialogu
     * ChooseMenuItemDialog v parametru hs.
     *
     * @param hs
     */
    protected void fillMenuItems(HashSet<String> hs) {
        this.hs = hs;
        jTextFieldMenuItems.setText(Integer.toString(hs.size()));
    }

    /**
     * Metoda cisti vsechny vstupni pole formulare a nastavuje pocet vybranych polozek menu na 0.
     */
    @Override
    protected void clearFields() {
        Validator.clearTextField(jTextFieldMenuItems);
        Validator.clearTextField(jTextFieldSum);
        Validator.clearTextField(jTextFieldCoefficient);
        jTextFieldMenuItems.setText("0");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        billPanel = new BackgroundPanel();
        jTextFieldDiscountType = new javax.swing.JTextField();
        jTextFieldSum = new javax.swing.JTextField();
        jTextFieldCoefficient = new javax.swing.JTextField();
        jTextFieldMenuItems = new javax.swing.JTextField();
        jLabelInfoText = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButtonSum = new javax.swing.JButton();
        jButtonCoefficient = new javax.swing.JButton();
        jButtonChooseMenuItems = new javax.swing.JButton();
        jButtonDiscountType = new javax.swing.JButton();
        jButtonCreateDiscountType = new javax.swing.JButton();
        jLabelCurrency = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabelTitle = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButtonDelete = new javax.swing.JButton();
        jButtonOK = new javax.swing.JButton();

        setBackground(javax.swing.UIManager.getDefaults().getColor("CheckBox.light"));

        billPanel.setBackground(javax.swing.UIManager.getDefaults().getColor("CheckBox.light"));
        billPanel.setOpaque(false);
        billPanel.setPreferredSize(new java.awt.Dimension(515, 470));

        jTextFieldDiscountType.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jTextFieldDiscountType.setMargin(new Insets(10, 10, 10, 10));

        jTextFieldSum.setEditable(false);
        jTextFieldSum.setBorder(null);

        jTextFieldCoefficient.setEditable(false);
        jTextFieldCoefficient.setBorder(null);

        jTextFieldMenuItems.setEditable(false);
        jTextFieldMenuItems.setBorder(null);

        jLabelInfoText.setFont(new java.awt.Font("Calibri", 1, 22));
        jLabelInfoText.setText("Nová sleva");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel1.setText("Srážka:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel2.setText("Koeficient:");

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 14));
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("Typ slevy:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel4.setText("Počet položek:");

        jPanel2.setOpaque(false);

        jButtonSum.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cz/cvut/fel/restauracefel/buttons/left.png"))); // NOI18N
        jButtonSum.setText(" Srážka");
        jButtonSum.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonSum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSumActionPerformed(evt);
            }
        });

        jButtonCoefficient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cz/cvut/fel/restauracefel/buttons/left.png"))); // NOI18N
        jButtonCoefficient.setText(" Koeficient");
        jButtonCoefficient.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonCoefficient.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButtonCoefficient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCoefficientActionPerformed(evt);
            }
        });

        jButtonChooseMenuItems.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cz/cvut/fel/restauracefel/buttons/left.png"))); // NOI18N
        jButtonChooseMenuItems.setText(" Přiřadit položky");
        jButtonChooseMenuItems.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonChooseMenuItems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChooseMenuItemsActionPerformed(evt);
            }
        });

        jButtonDiscountType.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cz/cvut/fel/restauracefel/buttons/left-red.png"))); // NOI18N
        jButtonDiscountType.setText(" Typ slevy");
        jButtonDiscountType.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonDiscountType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDiscountTypeActionPerformed(evt);
            }
        });

        jButtonCreateDiscountType.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cz/cvut/fel/restauracefel/buttons/left.png"))); // NOI18N
        jButtonCreateDiscountType.setText(" Nový typ slevy");
        jButtonCreateDiscountType.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonCreateDiscountType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreateDiscountTypeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonCreateDiscountType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonChooseMenuItems, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonCoefficient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonSum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonDiscountType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonDiscountType, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSum, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCoefficient, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonChooseMenuItems, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCreateDiscountType, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabelCurrency.setText(",- CZK");

        jLabel5.setText("%");

        javax.swing.GroupLayout billPanelLayout = new javax.swing.GroupLayout(billPanel);
        billPanel.setLayout(billPanelLayout);
        billPanelLayout.setHorizontalGroup(
            billPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(billPanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(billPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(billPanelLayout.createSequentialGroup()
                        .addGroup(billPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jTextFieldDiscountType, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(billPanelLayout.createSequentialGroup()
                                .addGroup(billPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(billPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldMenuItems))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, billPanelLayout.createSequentialGroup()
                                        .addGroup(billPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel2))
                                        .addGap(38, 38, 38)
                                        .addGroup(billPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextFieldCoefficient)
                                            .addComponent(jTextFieldSum, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(billPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabelCurrency, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))))
                        .addGap(54, 54, 54)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))
                    .addComponent(jLabelInfoText))
                .addContainerGap())
        );
        billPanelLayout.setVerticalGroup(
            billPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(billPanelLayout.createSequentialGroup()
                .addGroup(billPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(billPanelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabelInfoText)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(4, 4, 4)
                        .addComponent(jTextFieldDiscountType, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addGroup(billPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldSum, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelCurrency))
                        .addGap(39, 39, 39)
                        .addGroup(billPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextFieldCoefficient, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(39, 39, 39)
                        .addGroup(billPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextFieldMenuItems, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(billPanelLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        jLabelTitle.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTitle.setFont(new java.awt.Font("Tahoma", 0, 18));
        jLabelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitle.setText("Vytvořit novou slevu");
        jLabelTitle.setOpaque(true);

        jPanel3.setOpaque(false);

        jButtonDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cz/cvut/fel/restauracefel/buttons/ko.png"))); // NOI18N
        jButtonDelete.setText("  Vymazat");
        jButtonDelete.setToolTipText("Vymazat pole účtu");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        jButtonOK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cz/cvut/fel/restauracefel/buttons/ok.png"))); // NOI18N
        jButtonOK.setText("  OK");
        jButtonOK.setToolTipText("Vložit účet");
        jButtonOK.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButtonOK.setMargin(new java.awt.Insets(2, 0, 2, 0));
        jButtonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonOK, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonOK, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 832, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(billPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(billPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCoefficientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCoefficientActionPerformed
        KeyboardDialog keyboard = new KeyboardDialog(parent, true);
        keyboard.setLocation(point);
        keyboard.setTextField(jTextFieldCoefficient);
        keyboard.setVisible(true);
}//GEN-LAST:event_jButtonCoefficientActionPerformed

    private void jButtonSumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSumActionPerformed
        KeyboardDialog keyboard = new KeyboardDialog(parent, true);
        keyboard.setLocation(point);
        keyboard.setTextField(jTextFieldSum);
        keyboard.setVisible(true);
    }//GEN-LAST:event_jButtonSumActionPerformed

    private void jButtonChooseMenuItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChooseMenuItemsActionPerformed
        try {
            chooseMenuItemsDialog = new ChooseMenuItemsDialog(parent, true, this);
            chooseMenuItemsDialog.setLocation(point);
            chooseMenuItemsDialog.setVisible(true);
            refresh();
        } catch (FileNotFoundException fnfe) {
            JOptionPane.showMessageDialog(this, "Konfigurační soubor \"" + ConfigParser.getConfigFile() + "\" nebyl nalezen.", "Chyba", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Nelze navázat spojení se serverem.", "Chyba komunikace", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonChooseMenuItemsActionPerformed

    private void jButtonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKActionPerformed
        ValidEnum i = isValidInputComplex();
        switch (i) {
            case Spravne:
                try {
                    int discountTypeId = ServiceFacade.getInstance().getDiscountTypeByName(jTextFieldDiscountType.getText()).getDiscountTypeId();
                    double amount = Double.parseDouble(jTextFieldSum.getText());
                    double coefficient = Double.parseDouble(jTextFieldCoefficient.getText());
                    Iterator it = hs.iterator();
                    while (it.hasNext()) {
                        String name = (String) it.next();
                        int menuItemId = ServiceFacade.getInstance().getMenuItemByName(name).getMenuItemId();
                        ServiceFacade.getInstance().createDiscount(discountTypeId, menuItemId, amount, coefficient);
                    }
                } catch (FileNotFoundException fnfe) {
                    JOptionPane.showMessageDialog(this, "Konfigurační soubor \"" + ConfigParser.getConfigFile() + "\" nebyl nalezen.", "Chyba", JOptionPane.ERROR_MESSAGE);
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, "Nelze navázat spojení se serverem.", "Chyba komunikace", JOptionPane.ERROR_MESSAGE);
                }
                clearFields();
                break;
            case Sleva:
                JOptionPane.showMessageDialog(this, "Musí být vybrán typ slevy.", "Přiřazení slevy", JOptionPane.INFORMATION_MESSAGE);
                break;
            case NezaporneCislo:
                JOptionPane.showMessageDialog(this, "Srážka z ceny musí být nezáporné číslo.", "Přiřazení slevy", JOptionPane.INFORMATION_MESSAGE);
                break;
            case KoeficientNezaporny:
                JOptionPane.showMessageDialog(this, "Koeficient slevy musí být celé nezáporné číslo.", "Přiřazení slevy", JOptionPane.INFORMATION_MESSAGE);
                break;
            case JednaPolozka:
                JOptionPane.showMessageDialog(this, "Sleva musí být uplatněna alespoň na 1 položku", "Přiřazení slevy", JOptionPane.INFORMATION_MESSAGE);
                break;
            default:
                break;
        }
}//GEN-LAST:event_jButtonOKActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        clearFields();
}//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jButtonDiscountTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDiscountTypeActionPerformed
        try {
            chooseDiscountTypeDialog = new ChooseDiscountTypeDialog(parent, true, jTextFieldDiscountType, -1);
            chooseDiscountTypeDialog.setLocation(point);
            chooseDiscountTypeDialog.setVisible(true);
            refresh();
        } catch (EmptyListException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), ex.getTitle(), JOptionPane.INFORMATION_MESSAGE);
        } catch (FileNotFoundException fnfe) {
            JOptionPane.showMessageDialog(this, "Konfigurační soubor \"" + ConfigParser.getConfigFile() + "\" nebyl nalezen.", "Chyba", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Nelze navázat spojení se serverem.", "Chyba komunikace", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonDiscountTypeActionPerformed

    private void jButtonCreateDiscountTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreateDiscountTypeActionPerformed
        createDiscountTypeForm = new CreateDiscountTypeForm(parent, statusBar, this);
        parent.panel.getViewport().add(createDiscountTypeForm);
        parent.panel.repaint();
        parent.panel.validate();
        parent.refreshWindowLayout();
    }//GEN-LAST:event_jButtonCreateDiscountTypeActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel billPanel;
    private javax.swing.JButton jButtonChooseMenuItems;
    private javax.swing.JButton jButtonCoefficient;
    private javax.swing.JButton jButtonCreateDiscountType;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonDiscountType;
    private javax.swing.JButton jButtonOK;
    private javax.swing.JButton jButtonSum;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelCurrency;
    private javax.swing.JLabel jLabelInfoText;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextFieldCoefficient;
    private javax.swing.JTextField jTextFieldDiscountType;
    private javax.swing.JTextField jTextFieldMenuItems;
    private javax.swing.JTextField jTextFieldSum;
    // End of variables declaration//GEN-END:variables

}
