package cz.cvut.fel.restauracefel.hibernate;
// Generated 17.7.2011 22:33:15 by Hibernate Tools 3.2.1.GA

import java.util.List;


/**
 * Attendance generated by hbm2java
 */
public class Attendance extends DBEntity implements java.io.Serializable {

    private static final long serialVersionUID = 1L;
    private int idAttendance;
    private int idUser;
    private int idWorkshift;

    public Attendance() {
    }

    public Attendance(int idAttendance, int idUser) {
        this.idAttendance = idAttendance;
        this.idUser = idUser;

    }

    public Attendance(int idAttendance, int idUser, int idWorkshift) {
        this.idAttendance = idAttendance;
        this.idUser = idUser;
        this.idWorkshift = idWorkshift;
    }

    public int getIdAttendance() {
        return this.idAttendance;
    }

    public void setIdAttendance(int idAttendance) {
        this.idAttendance = idAttendance;
    }

    public int getIdUser() {
        return this.idUser;
    }

    public void setIdUser(int idUser) {
        this.idUser = idUser;
    }

    public int getIdWorkshift() {
        return this.idWorkshift;
    }

    public void setIdWorkshift(int idWorkshift) {
        this.idWorkshift = idWorkshift;
    }

    public void create() {
        create(this);
    }
    
    public static List findByWorkShiftId(int idWorkshift){
        String query = "from Attendance att where att.idWorkshift = :id1";
        String[] paramNames = new String[]{"id1"};
        String[] paramTypes = new String[]{"Integer"};
        Integer[] paramValues = new Integer[]{idWorkshift};

        List res = executeQuery(query, paramNames, paramTypes, paramValues);
        if (res == null || res.isEmpty()) {
            return null;
        }
        return res;
    }
    
    public static Attendance findById(int idAttendance){
        String query = "from Attendance att where att.idWorkshift = :id1";
        String[] paramNames = new String[]{"id1"};
        String[] paramTypes = new String[]{"Integer"};
        Integer[] paramValues = new Integer[]{idAttendance};

        List res = executeQuery(query, paramNames, paramTypes, paramValues);
        if (res == null || res.isEmpty()) {
            return null;
        }
        return (Attendance)res.get(0);
    }
    
    public void delete(){
        delete(this);
    }
}
