package cz.cvut.fel.restauracefel.hibernate;
// Generated 16.3.2009 21:36:54 by Hibernate Tools 3.2.1.GA

import java.util.List;

/**
 * MaterialType generated by hbm2java
 */
public class MaterialType extends DBEntity {

    private static final long serialVersionUID = -8935311145309357906L;
    
    private Integer materialTypeId;
    private String name;
    private String note;
    private int isDeleted;

    public MaterialType() {
    }

    public MaterialType(String name, int isDeleted) {
        this.name = name;
        this.isDeleted = isDeleted;
    }

    public MaterialType(String name, String note, int isDeleted) {
        this.name = name;
        this.note = note;
        this.isDeleted = isDeleted;
    }

    public Integer getMaterialTypeId() {
        return this.materialTypeId;
    }

    public void setMaterialTypeId(Integer materialTypeId) {
        this.materialTypeId = materialTypeId;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getNote() {
        return this.note;
    }

    public void setNote(String note) {
        this.note = note;
    }

    public int getIsDeleted() {
        return isDeleted;
    }

    public void setIsDeleted(int isDeleted) {
        this.isDeleted = isDeleted;
    }
    
    public void create() {
        create(this);
    }

    public void update() {
        update(this);
    }

    public void delete() {
        delete(this);
    }

    public static MaterialType findById(Integer id) {
        //return (MaterialType) findById("MaterialType", "materialTypeId", id);
        return (MaterialType) findByIdNotDeleted("MaterialType", "materialTypeId", id, "isDeleted", 0);
    }

    public static MaterialType findByName(String name) {
        //return (MaterialType) findByStringName("MaterialType", "name", name);
        return (MaterialType) findByStringNameNotDeleted("MaterialType", "name", name, "isDeleted", 0);
    }

    //vrati vsechny druhy materialu, ktere nejsou oznaceny jako smazane
    public static List findAll(){
        return findAllNotDeleted("MaterialType", "isDeleted", 0);
    }
}


