package cz.cvut.fel.restauracefel.hibernate;
// Generated 17.7.2011 22:33:15 by Hibernate Tools 3.2.1.GA

import java.util.List;

/**
 * Templatelist generated by hbm2java
 */
public class TemplateList extends DBEntity implements java.io.Serializable {

    private static final long serialVersionUID = 1L;
    private int idTemplatelist;
    private int idTemplate;
    private int idTypeworkshift;
    private int isDeleted;

    public TemplateList() {
    }

    public TemplateList(int id) {
        this.idTemplatelist = id;
    }

    public TemplateList(int id, int idTemplate, int idTypeworkshift, int isDeleted) {
        this.idTemplatelist = id;
        this.idTemplate = idTemplate;
        this.idTypeworkshift = idTypeworkshift;
        this.isDeleted = isDeleted;
    }

    public int getIdTemplatelist() {
        return idTemplatelist;
    }

    public void setIdTemplatelist(int id) {
        this.idTemplatelist = id;
    }

    /**
     * @return the idTemplate
     */
    public int getIdTemplate() {
        return idTemplate;
    }

    /**
     * @param idTemplate the idTemplate to set
     */
    public void setIdTemplate(int idTemplate) {
        this.idTemplate = idTemplate;
    }

    /**
     * @return the idTypeworkshift
     */
    public int getIdTypeworkshift() {
        return idTypeworkshift;
    }

    /**
     * @param idTypeworkshift the idTypeworkshift to set
     */
    public void setIdTypeworkshift(int idTypeworkshift) {
        this.idTypeworkshift = idTypeworkshift;
    }

    /**
     * @return the isDeleted
     */
    public int getIsDeleted() {
        return isDeleted;
    }

    /**
     * @param isDeleted the isDeleted to set
     */
    public void setIsDeleted(int isDeleted) {
        this.isDeleted = isDeleted;
    }

    public List findAll() {
        return findAllNotDeleted("Templatelist", "isDeleted", 0);
    }

    public void create() {
        create(this);
    }

    public void delete() {
        delete(this);
    }

    public static List getTemplateListByTemplateId(Integer idTemplate) {
        String[] paramNames = {"id"};
        String[] paramTypes = {"Integer"};
        Object[] paramValues = {idTemplate};

        String className = "TemplateList";

        //String idParamName = className.substring(0, 1).toLowerCase() + className.substring(1) + "ID";
        String idParamName = "idTemplate";

        // POZOR, tady parametrem neni nazev tabulky a sloupecku, ale nazev tridy a jejich atributu
        List res = executeQuery("from " + className + " x where x." + idParamName + " = :id", paramNames, paramTypes, paramValues);

        if (res == null || res.isEmpty()) {
            return null;
        }

        return res;

    }
}
