package cz.cvut.fel.restauracefel.hibernate;
// Generated 16.3.2009 21:36:54 by Hibernate Tools 3.2.1.GA

import java.io.Serializable;


/**
 * Table generated by hbm2java
 */
public class Table implements Serializable {

    private static final long serialVersionUID = 2722674881805881779L;

    private Integer tableId;
    private int tableNumber;
    private int numberOfPlaces;
    private int isDeleted;

    public Table() {
    }

    public Table(int tableNumber, int numberOfPlaces, int isDeleted) {
        this.tableNumber = tableNumber;
        this.numberOfPlaces = numberOfPlaces;
        this.isDeleted = isDeleted;
    }

    public Integer getTableId() {
        return this.tableId;
    }

    public void setTableId(Integer tableId) {
        this.tableId = tableId;
    }

    public int getTableNumber() {
        return this.tableNumber;
    }

    public void setTableNumber(int tableNumber) {
        this.tableNumber = tableNumber;
    }

    public int getNumberOfPlaces() {
        return this.numberOfPlaces;
    }

    public void setNumberOfPlaces(int numberOfPlaces) {
        this.numberOfPlaces = numberOfPlaces;
    }

    public int getIsDeleted() {
        return isDeleted;
    }

    public void setIsDeleted(int isDeleted) {
        this.isDeleted = isDeleted;
    }

}


