package cz.cvut.fel.restauracefel.hibernate;
// Generated 17.7.2011 22:33:15 by Hibernate Tools 3.2.1.GA

import java.util.List;

/**
 * Template generated by hbm2java
 */
public class Template implements java.io.Serializable {

    private static final long serialVersionUID = 1L;
    private int idTemplate;
    private String name;
    private int status;
    private int isDeleted;

    public Template() {
    }

    public Template(int idTemplate) {
        this.idTemplate = idTemplate;
    }

    public Template(int idTemplate, String name, int status, int isDeleted) {
        this.idTemplate = idTemplate;
        this.name = name;
        this.status = status;
        this.isDeleted = isDeleted;
    }

    public int getIdTemplate() {
        return this.idTemplate;
    }

    public void setIdTemplate(int idTemplate) {
        this.idTemplate = idTemplate;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    /**
     * @return the isDeleted
     */
    public int getIsDeleted() {
        return isDeleted;
    }

    /**
     * @param isDeleted the isDeleted to set
     */
    public void setIsDeleted(int isDeleted) {
        this.isDeleted = isDeleted;
    }

    public int getStatus() {
        return this.status;
    }

    public void setStatus(int status) {
        this.status = status;
    }
}
