package cz.cvut.fel.restauracefel.hibernate;
// Generated 17.7.2011 22:33:15 by Hibernate Tools 3.2.1.GA

import java.util.List;


/**
 * Templatelist generated by hbm2java
 */
public class TemplateList implements java.io.Serializable {

    private static final long serialVersionUID = 1L;
    private int idTemplatelist;
    private int idTemplate;
    private int idTypeworkshift;
    private int isDeleted;

    public TemplateList() {
    }

    public TemplateList(int id) {
        this.idTemplatelist = id;
    }

    public TemplateList(int id, int idTemplate, int idTypeworkshift, int isDeleted) {
        this.idTemplatelist = id;
        this.idTemplate = idTemplate;
        this.idTypeworkshift = idTypeworkshift;
        this.isDeleted = isDeleted;
    }

    public int getIdTemplatelist() {
        return idTemplatelist;
    }

    public void setIdTemplatelist(int id) {
        this.idTemplatelist = id;
    }

    /**
     * @return the idTemplate
     */
    public int getIdTemplate() {
        return idTemplate;
    }

    /**
     * @param idTemplate the idTemplate to set
     */
    public void setIdTemplate(int idTemplate) {
        this.idTemplate = idTemplate;
    }

    /**
     * @return the idTypeworkshift
     */
    public int getIdTypeworkshift() {
        return idTypeworkshift;
    }

    /**
     * @param idTypeworkshift the idTypeworkshift to set
     */
    public void setIdTypeworkshift(int idTypeworkshift) {
        this.idTypeworkshift = idTypeworkshift;
    }

    /**
     * @return the isDeleted
     */
    public int getIsDeleted() {
        return isDeleted;
    }

    /**
     * @param isDeleted the isDeleted to set
     */
    public void setIsDeleted(int isDeleted) {
        this.isDeleted = isDeleted;
    }
        
}
