package cz.cvut.fel.restauracefel.restauracefel.gui;

import java.io.FileNotFoundException;
import java.util.HashSet;
import java.util.Iterator;
import javax.swing.JOptionPane;
import cz.cvut.fel.restauracefel.library.service.ConfigParser;
import cz.cvut.fel.restauracefel.library.service.EmptyListException;
import cz.cvut.fel.restauracefel.library.service.Validator;
import cz.cvut.fel.restauracefel.library.service.CommonServiceFacade;
import cz.cvut.fel.restauracefel.library.service.LocalizationManager;
import cz.cvut.fel.restauracefel.restauracefel.main.Main;

/**
 * Trida reprezentujici GUI formular pro zmenu pristupovych prav.
 *
 * @author Tomas Hnizdil
 */
public class AssignRightForm extends AbstractForm {

    private ChooseRoleDialog chooseRoleDialog = null;
    private ChooseRightDialog chooseRightDialog = null;
    private StatusBar statusBar = null;
    private MainFrame parent = null;
    private HashSet<String> addedRights = null;
    private HashSet<String> removedRights = null;

    /**
     * Konstruktor tridy AssignRightForm.
     *
     * @param parent
     * @param bar
     */
    public AssignRightForm(MainFrame parent, StatusBar bar) {
        this.parent = parent;
        this.statusBar = bar;
        initComponents();

        LocalizationManager manager = LocalizationManager.getInstance();
        manager.localizeLabel(Main.DEFAULT_BUNDLE_BASE_NAME, "EditRightsLabel", jLabelTitle);
        manager.localizeLabel(Main.DEFAULT_BUNDLE_BASE_NAME, "AccessRightsLabel", jLabelInfoText);

        manager.localizeLabel(Main.DEFAULT_BUNDLE_BASE_NAME, "AddedRightsCountLabel", jLabel1);
        manager.localizeLabel(Main.DEFAULT_BUNDLE_BASE_NAME, "RemovedRightsCountLabel", jLabel2);
        manager.localizeLabel(Main.DEFAULT_BUNDLE_BASE_NAME, "RoleLabel", jLabel3);

        manager.localizeButton(Main.DEFAULT_BUNDLE_BASE_NAME, "PersonButton", jButtonPerson);
        manager.localizeButton(Main.DEFAULT_BUNDLE_BASE_NAME, "AddRightsButton", jButtonAddRights);
        manager.localizeButton(Main.DEFAULT_BUNDLE_BASE_NAME, "RemoveRightsButton", jButtonRemoveRights);

        manager.localizeButton(Main.DEFAULT_BUNDLE_BASE_NAME, "OkButton", jButtonOK);
        manager.localizeButton(Main.DEFAULT_BUNDLE_BASE_NAME, "DeleteButton", jButtonDelete);

        refresh();
        clearFields();
    }

    /**
     * Metoda prenastavuje statusBar.
     *
     */
    @Override
    protected void refresh() {
        statusBar.setMessage("Tento formulář slouží k upravování přístupových práv.");
    }

    /**
     * Metoda kontrolujici spravnost vyplnenych udaju.
     *
     * @return Vraci index urcujici vstupni komponentu, ktera obsahuje
     * neplatny vstup. Pokud je vse vporadku tak navraci 0.
     */
    @Override
    protected int isValidInput() {
        if (!Validator.isText(jTextFieldRole)) {
            return 1;
        }
        if (!Validator.isPositiveInt(jTextFieldAddedRights) && !Validator.isPositiveInt(jTextFieldRemovedRights)) {
            return 2;
        }
        return 0;
    }

    /**
     * Metoda ulozi seznam vybranych prav k pridani predavany z dialogu
     * ChooseRightDialog v parametru addedRights.
     *
     * @param addedRights
     */
    protected void fillAddedRights(HashSet<String> addedRights) {
        this.addedRights = addedRights;
        jTextFieldAddedRights.setText(Integer.toString(addedRights.size()));
    }

    /**
     * Metoda ulozi seznam vybranych prav k odebrani predavany z dialogu
     * ChooseRightDialog v parametru removedRights.
     *
     * @param addedRights
     */
    protected void fillRemovedRights(HashSet<String> removedRights) {
        this.removedRights = removedRights;
        jTextFieldRemovedRights.setText(Integer.toString(removedRights.size()));
    }

    /**
     * Metoda cisti vsechny vstupni formulare, formular pro datum nastavuje na
     * aktualni datum a u comboBoxu nastavuje aktualni vybranou polozku na
     * prvni polozku daneho comboBoxu.
     */
    @Override
    protected void clearFields() {
        Validator.clearTextField(jTextFieldRole);
        jTextFieldAddedRights.setText("0");
        jTextFieldRemovedRights.setText("0");
        removedRights = null;
        addedRights = null;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        billPanel = new BackgroundPanelBill( );
        jTextFieldDiscountType5 = new javax.swing.JTextField();
        jLabelInfoText = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButtonAddRights = new javax.swing.JButton();
        jButtonPerson = new javax.swing.JButton();
        jButtonRemoveRights = new javax.swing.JButton();
        jTextFieldAddedRights = new javax.swing.JTextField();
        jTextFieldRole = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldRemovedRights = new javax.swing.JTextField();
        jLabelTitle = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButtonDelete = new javax.swing.JButton();
        jButtonOK = new javax.swing.JButton();

        billPanel.setForeground(java.awt.SystemColor.activeCaptionBorder);
        billPanel.setOpaque(false);

        jTextFieldDiscountType5.setEditable(false);
        jTextFieldDiscountType5.setBorder(null);

        jLabelInfoText.setFont(new java.awt.Font("Calibri", 1, 22));
        jLabelInfoText.setText("Přístupová práva");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel1.setText("Počet přidávaných práv:");

        jPanel2.setOpaque(false);

        jButtonAddRights.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cz/cvut/fel/restauracefel/buttons/left.png"))); // NOI18N
        jButtonAddRights.setText("Přidat práva");
        jButtonAddRights.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonAddRights.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddRightsActionPerformed(evt);
            }
        });

        jButtonPerson.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cz/cvut/fel/restauracefel/buttons/left-red.png"))); // NOI18N
        jButtonPerson.setText("Uživatelské role");
        jButtonPerson.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPersonActionPerformed(evt);
            }
        });

        jButtonRemoveRights.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cz/cvut/fel/restauracefel/buttons/left.png"))); // NOI18N
        jButtonRemoveRights.setText("Odebrat práva");
        jButtonRemoveRights.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonRemoveRights.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoveRightsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButtonRemoveRights, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonPerson, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonAddRights, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAddRights, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonRemoveRights, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(143, 143, 143))
        );

        jTextFieldAddedRights.setEditable(false);
        jTextFieldAddedRights.setBorder(null);

        jTextFieldRole.setEditable(false);
        jTextFieldRole.setBorder(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel3.setText("Role:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel2.setText("Počet odebíraných práv:");

        jTextFieldRemovedRights.setEditable(false);
        jTextFieldRemovedRights.setBorder(null);

        javax.swing.GroupLayout billPanelLayout = new javax.swing.GroupLayout(billPanel);
        billPanel.setLayout(billPanelLayout);
        billPanelLayout.setHorizontalGroup(
            billPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(billPanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(billPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(billPanelLayout.createSequentialGroup()
                        .addGroup(billPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(billPanelLayout.createSequentialGroup()
                                .addGap(151, 151, 151)
                                .addComponent(jTextFieldDiscountType5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(billPanelLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(billPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(10, 10, 10)
                                .addGroup(billPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextFieldRemovedRights, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldAddedRights, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                                    .addComponent(jTextFieldRole, javax.swing.GroupLayout.Alignment.LEADING)))
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))
                    .addGroup(billPanelLayout.createSequentialGroup()
                        .addComponent(jLabelInfoText)
                        .addContainerGap(361, Short.MAX_VALUE))))
        );
        billPanelLayout.setVerticalGroup(
            billPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(billPanelLayout.createSequentialGroup()
                .addGroup(billPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(billPanelLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabelInfoText)
                        .addGap(46, 46, 46)
                        .addGroup(billPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldRole, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(billPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldAddedRights, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(billPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldRemovedRights, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(62, 62, 62)
                        .addComponent(jTextFieldDiscountType5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(billPanelLayout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabelTitle.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTitle.setFont(new java.awt.Font("Tahoma", 0, 18));
        jLabelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitle.setText("Upravit přístupová práva");
        jLabelTitle.setOpaque(true);

        jPanel1.setOpaque(false);

        jButtonDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cz/cvut/fel/restauracefel/buttons/ko.png"))); // NOI18N
        jButtonDelete.setText("  Vymazat");
        jButtonDelete.setToolTipText("Vymazat pole účtu");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        jButtonOK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cz/cvut/fel/restauracefel/buttons/ok.png"))); // NOI18N
        jButtonOK.setText("  OK");
        jButtonOK.setToolTipText("Vložit účet");
        jButtonOK.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButtonOK.setMargin(new java.awt.Insets(2, 0, 2, 0));
        jButtonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonOK, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonOK, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 810, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(billPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(billPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        clearFields();
}//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jButtonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKActionPerformed
        int i = isValidInput();
        switch (i) {
            case 0:
                try {
                    int roleId = CommonServiceFacade.getInstance().getRoleByName(jTextFieldRole.getText()).getRoleId();
                    Iterator it;
                    if (addedRights != null) {
                        it = addedRights.iterator();
                        while (it.hasNext()) {
                            String name = (String) it.next();
                            int rightId = CommonServiceFacade.getInstance().getRightByName(name).getRightId();
                            CommonServiceFacade.getInstance().createRoleRight(roleId, rightId);
                        }
                    }

                    if (removedRights != null) {
                        it = removedRights.iterator();
                        while (it.hasNext()) {
                            String name = (String) it.next();
                            int rightId = CommonServiceFacade.getInstance().getRightByName(name).getRightId();
                            CommonServiceFacade.getInstance().deleteRoleRight(roleId, rightId);
                        }
                    }
                } catch (FileNotFoundException fnfe) {
                    JOptionPane.showMessageDialog(this, "Konfigurační soubor \"" + ConfigParser.getConfigFile() + "\" nebyl nalezen.", "Chyba", JOptionPane.ERROR_MESSAGE);
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, "Nelze navázat spojení se serverem.", "Chyba komunikace", JOptionPane.ERROR_MESSAGE);
                }
                clearFields();
                break;
            case 1:
                JOptionPane.showMessageDialog(this, "Musí být vybrána uživatelská role.", "Úprava přístupových práv", JOptionPane.INFORMATION_MESSAGE);
                break;
            case 2:
                JOptionPane.showMessageDialog(this, "Musí být přidáváno nebo odebíráno aspoň 1 přístupové právo.", "Úprava přístupových práv", JOptionPane.INFORMATION_MESSAGE);
                break;
            default:
                break;
        }
}//GEN-LAST:event_jButtonOKActionPerformed

    private void jButtonRemoveRightsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoveRightsActionPerformed
        if (isValidInput() == 1) {
            JOptionPane.showMessageDialog(this, "K odebrání přístupových práv musí být vybrána uživatelská role.", "Odebrání přístupových práv", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        try {
            int roleId = CommonServiceFacade.getInstance().getRoleByName(jTextFieldRole.getText()).getRoleId();
            chooseRightDialog = new ChooseRightDialog(parent, true, this, roleId);
            chooseRightDialog.setLocation(550, 210);
            chooseRightDialog.setVisible(true);
            refresh();
        } catch (EmptyListException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), ex.getTitle(), JOptionPane.INFORMATION_MESSAGE);
        } catch (FileNotFoundException fnfe) {
            JOptionPane.showMessageDialog(this, "Konfigurační soubor \"" + ConfigParser.getConfigFile() + "\" nebyl nalezen.", "Chyba", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Nelze navázat spojení se serverem.", "Chyba komunikace", JOptionPane.ERROR_MESSAGE);
        }
}//GEN-LAST:event_jButtonRemoveRightsActionPerformed

    private void jButtonPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPersonActionPerformed
        try {
            chooseRoleDialog = new ChooseRoleDialog(parent, true, jTextFieldRole);
            chooseRoleDialog.setLocation(550, 210);
            chooseRoleDialog.setVisible(true);
            refresh();
        } catch (EmptyListException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), ex.getTitle(), JOptionPane.INFORMATION_MESSAGE);
        } catch (FileNotFoundException fnfe) {
            JOptionPane.showMessageDialog(this, "Konfigurační soubor \"" + ConfigParser.getConfigFile() + "\" nebyl nalezen.", "Chyba", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Nelze navázat spojení se serverem.", "Chyba komunikace", JOptionPane.ERROR_MESSAGE);
        }
}//GEN-LAST:event_jButtonPersonActionPerformed

    private void jButtonAddRightsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddRightsActionPerformed
        try {
            chooseRightDialog = new ChooseRightDialog(parent, true, this, 0);
            chooseRightDialog.setLocation(550, 210);
            chooseRightDialog.setVisible(true);
            refresh();
        } catch (FileNotFoundException fnfe) {
            JOptionPane.showMessageDialog(this, "Konfigurační soubor \"" + ConfigParser.getConfigFile() + "\" nebyl nalezen.", "Chyba", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Nelze navázat spojení se serverem.", "Chyba komunikace", JOptionPane.ERROR_MESSAGE);
        }
}//GEN-LAST:event_jButtonAddRightsActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel billPanel;
    private javax.swing.JButton jButtonAddRights;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonOK;
    private javax.swing.JButton jButtonPerson;
    private javax.swing.JButton jButtonRemoveRights;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelInfoText;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextFieldAddedRights;
    private javax.swing.JTextField jTextFieldDiscountType5;
    private javax.swing.JTextField jTextFieldRemovedRights;
    private javax.swing.JTextField jTextFieldRole;
    // End of variables declaration//GEN-END:variables
}
